# Copyright Louis Dionne 2013-2017
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
os: linux # Jobs are on Linux unless specified otherwise
dist: trusty # Jobs are on Trusty unless specified otherwise
sudo: required

matrix:
  include:
    ##########################################################################
    # Build with the main configuration on all the supported compilers
    #
    # Note that we only use the memory checker on the main configuration to
    # speed up Travis builds.
    ##########################################################################
    # GCC 7
    - env: UNIT_TESTS=true COMPILER=g++-7 ENABLE_MEMCHECK=false
      addons: { apt: { packages: ["g++-7", "valgrind", "boost1.67", "libmariadbclient-dev" ], sources: [{sourceline: 'ppa:mhier/libboost-latest'}, "ubuntu-toolchain-r-test"] } }

install:
  ############################################################################
  # All the dependencies are installed in ${HOME}/deps/
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version
  -
before_script:
  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  - cd "${TRAVIS_BUILD_DIR}"
  - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})

  - mysql -u root < test/init.sql

services: mysql
script:
  ############################################################################
  # Build and run the unit tests and examples.
  ############################################################################
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      (cd build && make tests -j2 -k) &&
      if [[ "${ENABLE_MEMCHECK}" == "true" ]]; then
        (cd build && ctest --output-on-failure -j2 -D ExperimentalMemCheck)
      else
        (cd build && ctest --output-on-failure -j2)
      fi
    fi
  - (cd build && make -j2 -k) || exit 1
  - (cd build && echo "show databases; select 5+10; " | ./mariadb_async_multi_query) || exit 1
  - (cd build && ./mariadb_async_single_query) || exit 1
